### ISSUE TITLE
Unable to run tests on two instances of OpenFin application in parallel

### ISSUE THREAD

**Issue by abhishek-pandey** [openfin/hello-openfin-selenium-java-example#1]
Here is my sample code. It uses TestNG data provider to implement parallelism. The two HelloOpenFin app.json files that i used have different uuid's and devtool ports.

``` java
package com.openfin;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

public class Driver {
    @Test(dataProvider = "dp")
    public void ap(String a, String b, String c, String d) throws MalformedURLException, InterruptedException {
        startSession(a, b, c, d);
    }

    @DataProvider(name = "dp", parallel = true)
    public Object[][] dp() {
        String basePath = "C:/hello-openfin-selenium-java-example/lib/";
        return new Object[][] {
                { basePath + "OpenFinRVM1.exe", "--config=" + basePath + "apps1.json", "localhost:9090", "http://localhost:9515" },
                { basePath + "OpenFinRVM1.exe", "--config=" + basePath + "apps2.json", "localhost:9091", "http://localhost:9516" } };
    }

    public void startSession(String a, String b, String c, String d) throws MalformedURLException, InterruptedException {
        String execPath = a;
        String execArgs = b;
        String debuggerAddress = c;
        String remoteDriverURL = d;

        ChromeOptions options = new ChromeOptions();
        options.setBinary(new File(execPath));
        options.addArguments(execArgs);
        options.setExperimentalOption("debuggerAddress", debuggerAddress);
        options.setExperimentalOption("forceDevToolsScreenshot", Boolean.TRUE);

        DesiredCapabilities capabilities = DesiredCapabilities.chrome();
        capabilities.setCapability(ChromeOptions.CAPABILITY, options);

        WebDriver driver = new RemoteWebDriver(new URL(remoteDriverURL), capabilities);
        switchWindow(driver, "Hello OpenFin", 30);
        driver.findElement(By.id("desktop-notification")).click();
    }

    public boolean switchWindow(WebDriver webDriver, String windowTitle, int maxWaitInSeconds) throws InterruptedException {
        boolean found = false;
        long start = System.currentTimeMillis();
        while (!found) {
            for (String name : webDriver.getWindowHandles()) {
                webDriver.switchTo().window(name);
                if (webDriver.getTitle().equals(windowTitle)) {
                    found = true;
                    break;
                }
            }
            Thread.sleep(1000);
            if ((System.currentTimeMillis() - start) > maxWaitInSeconds * 1000) {
                break;
            }
        }

        if (!found) {
            System.out.println(windowTitle + " not found");
        }
        return found;
    }
}
```

The first session ran fine but the the driver for second session fails to find the devTools port:

![image](https://cloud.githubusercontent.com/assets/12640492/8323179/7d4708ec-1a5e-11e5-904b-2ff823bb8cc9.png)

**Comment by sagarwadhwa1** [comment]
I have been facing the same issue.
Seems like the **second instance** of **OpenFinRVM.exe** is not able to provide access of the devtools port to the chromedriver.

**Comment by wenjunche** [comment]
Thank you for the example code.   I will take a look today/tomorrow.

**Comment by wenjunche** [comment]
Hello

Here is what's going on:  when an application is launched (from app.json in this case), if version of Runtime specified in app.json is already running, RVM does not start another instance and the 2nd app just runs in the same instance of Runtime.  So, in your test case, the 2nd instance, with 90901 as debug port, never gets started.

I am able to have 2 instances of test running by specifying a different Runtime version, such as alpha, in app2.json:

``` javascript

"devtools_port": 9091,
    "runtime": {
        "arguments": "",
        "version": "alpha"
    },
```

Please let us know if you have questions
Thanks
Wenjun

**Comment by wenjunche** [comment]
Also, I just uploaded the latest version of OpenFinRVM.exe.

**Comment by abhishek-pandey** [comment]
Thanks Wenjun for the quick resolution. It works perfectly for two parallel sessions after changing the version in app.json. In our project we would like to run around ten parallel threads to speed up things.  Using the versions at https://developer.openfin.co/health/ may not help. How else can we achieve this?

-Abhishek

**Comment by wenjunche** [comment]
We have a new version of the Runtime,4.40.3.20, that supports multiple instances.  This version accepts a new argument: --security-realm=someString.   You need to assign an unique realm for each instance.  Here are the config I am using for testing:
 https://demoappdirectory.openf.in/desktop/config/apps/OpenFin/HelloOpenFin/alpha2.json
 https://demoappdirectory.openf.in/desktop/config/apps/OpenFin/HelloOpenFin/alpha3.json

Also, please specify 4.40.3.20 as Runtime version.

Please let's know if it works for you.

Thanks
Wenjun

**Comment by abhishek-pandey** [comment]
Thanks a lot Wenjun. That solves our problem.

-Abhishek

**Comment by Naveenhd51** [comment]
Hi Abhishek, can guide me how to sample code will work on TestNG
